matrix:
  include:
    - language: python
      sudo: required
      python:
        - '3.6'
      cache: apt
      addons:
        apt:
          packages:
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
      install:
        - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy=1.13.1
        - pip install nose
        - pip install -r requirements.txt
      script:
        - nosetests test
      deploy:
        provider: pypi
        user: nvictus
        password:
          secure: K3V+eyTfK1xJaEgQj1Nj+kFcdsFcDiKBOYiNDSqiDL2rMbCmd/ALLDft4481fBzKEK7ZWb8izVVSuOMG9+JnoYPj1jXkj2JUuBVNYmXAiyfZHAiCJPA0D+K/ckryCyvUisXXMhgA1JAWAzayfQdf81NODZWADp05zU2I5NeRNCpMl2l38MtePFZHJXj/ixHt60Ztbw4lvrMDaznhrKQRTNVXy0LV19p+2FrtNEe/lMJVFfFITJ9egOmOY2H9NYGPpGPpZvkQ1aBk8hfeEa9eKXbVkj9xmzyxMXwBETXvr0RciAP4swJeFrbnoI9zEiK/mFOEd7ExuOpqdOnVQnQY6nf8nPUgF6dSWa9RDG6pJhZQ1ZJl5H7pvXVvvLyygeVDNXCuTYGUMEP+G9mByOyLCixkBEf1ee0UyBwaIVHXCg7Ev1Vpn4utUxDMgvZugaSXKuPj+WQKwKZMc/zeIxFEmDO7a7rQrVQXv+sgTuMxIDr4bYEO4Qr94m5VAAFtFtA9VKtZGY9Fw9K24aW+tyiQRKW0KV7RKFSa+hRS/N+Hezuv6Dry/9B6KPazVtnxKRU7hB1ztxVYJxBAGeCdyaIyaHJ4O+MNFej14tHys55DmFqdtrq6b0kX2zqvcfaojbNbgOQlxRTX7fX8AHYyh5aOBrH60Amfbh8e4lsNeE25314=
        on:
          tags: true
          distributions: sdist bdist_wheel
          repo: higlass/higlass-python

    - language: node_js
      node_js:
        - "10"
      branches:
        only:
        - master
      before_deploy:
        - cd js
      deploy:
        provider: npm
        email: pkerpedjiev@gmail.com
        api_key:
          secure: gxFSh9DNZgA51xZVpr7MFLEV81ZzRhuEnmFmZ+rYZZ6eMKCwTB7qtnSdzTUHIS7V424gGzvATvG7DTj7gYlOWaRZrOQfo21ncyqbxeMRmZcAn5EyV8tl66sAjW/izv9WmcMeAYHdUKP4+8uXVfPn/aW57VwUWU+lsAr3u6eqJXjfieCML6h13QleOG3pHRPlWYe3C7QGF6CxzF+B0/pv6pM9UggMd38dIYfYHMgdbwoQs9ssYtnXpPSa0mgBQWMXUI8yi5n/HsXCtW+Ts//uR2jclpXnnlOU/o/xc7Qc70YdlQEumN+vq8xHZLX2SQO8Mg7h/dkZudOeE/n0BCLVgF+GVQhVsXICYF3u30xkpPe0VgSWs4GtSrRhi2E698s9lT11ONpQCJOqAEf+ywP5+xD0KX58rf3/sHUJUqIImE2xNLUgSsppxbADMvHbFmWsB5FVHhquUCRzjfz9+R0KBrN6mKNzXhUWEM267HglSW8oRTybXSK/UaqKK7l5nfoNgSTiOebIsEqu7d9XT92hZL8u4XAFbM3tetuh3ch8PDvsiEV50ISMUojhj+49c/CAaX07+noAQmlJ1W0SsQASbUDnQn8+cfPXU72UKxTydYaiNfO7xV2UDkmrrDWeElJwakX5cMoB9ck3RbCUWP9+hQXxDXLpy7mZB/bx0Sh/xvY=
        on:
          branch: master
          tags: true
          repo: higlass/higlass-python
