name: hg-jupyter
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.7
  - nodejs
  - multiprocess
  - fusepy
  - cython
  - cytoolz
  - sh
  - jupyterlab
  - flask
  - flask-cors
  - ipython
  - ipywidgets
  - requests
  - pip
  - pip:
      - clodius
      - slugid
      - simple-httpfs
